spring.datasource.url= jdbc:postgresql://192.168.0.67:5432/hfj-cdb
spring.datasource.username= postgres
spring.datasource.password = admin


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080
server.address=0.0.0.0